[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = {path = "../shared"}
anyhow = "1.0.75"
thiserror = "1.0.49"
serde_json = "1.0.107"
serde = {version="1.0.188", features = ["derive"]}