[package]
name = "egui_rust_web_experiments_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
thiserror = "1.0.49"
serde_json = "1.0.107"
serde = {version="1.0.188", features = ["derive"]}